version: '3.8'
services:
  my-sample-worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 8001:8000
    volumes:
      - storage:/storage
volumes:
  storage:
    name: my-sample-storage