version: '3.8'
services:
  my-sample-web:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 8000:8000
      - 8081:8080
    environment:
      - SERVER_PORT=8080
    volumes:
      - ./:/app